compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  docusaurus-plugin-image-zoom@1.0.1:
    peerDependencies:
      tslib: '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0.cjs

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
